### ISSUE TITLE
Adding a slideshow feature

### ISSUE THREAD

**Issue by gxhamster** [GDquest/godot-presentations#9]
**Adding a slideshow feature to autoplay the slides**

PS. i have done this locally but i have slow internet will try when i get fast internet to push these changes

**Comment by abitrolly** [comment]
So have you got a stronger internets? :D

**Comment by gxhamster** [comment]
No longer have the project. Man It has been over a year

**Comment by abitrolly** [comment]
Then I suggest to bury this issue until a new project arrives.

**Comment by NathanLovato** [comment]
Closing following the discussion.
